services:
  autoupdater:
    image: modelingevolution/autoupdater:latest
    restart: always
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "10"
    volumes:
      - /var/docker/production:/var/docker/production
      - /var/run/docker.sock:/var/run/docker.sock
